Iter13
RomanAVolodin/go-url-shortener pull request #14
Opened 2023-01-27 19:12 UTC by RomanAVolodin

2023-02-01 20:54 UTC, avhitrov requested changes
По коду все замечательно. 
Есть замечания по передаваемым/возвращаемым параметрам.
Из репозитория следует удалить `cmd/shortener/shortenertest`

2023-02-02 11:12 UTC, RomanAVolodin commented on internal/shortener/handlers/shortener_handlers.go
> +) (entities.ShortURL, int, error) {
Done

2023-02-02 11:22 UTC, RomanAVolodin commented on internal/shortener/repositories/repository.go
> +	GetByUserID(ctx context.Context, userID uuid.UUID) []entities.ShortURL
Done

2023-02-07 20:11 UTC, avhitrov approved these changes

2023-02-07 20:42 UTC, merged