iter14 mvp completed
RomanAVolodin/go-url-shortener pull request #15
Opened 2023-02-11 17:26 UTC by RomanAVolodin

2023-02-13 23:06 UTC, avhitrov requested changes
Data Race при удалении и аккумуляции идентификаторов. Предложение по организации канала, используемого для FanIn.

2023-02-13 23:06 UTC, avhitrov commented on internal/shortener/repositories/file_repository.go
> +	if err = encoder.Encode(&repo.Storage); err != nil {
Вот тут будут гонки.

2023-02-13 23:06 UTC, avhitrov commented on internal/shortener/repositories/db_repository.go
> +		for range ticker.C {
Очень правильно был создан мьютекс для защиты localStorage, но без RLock-RUnlock в этом блоке мьютекс, описанный ниже не защитит от гонок.

2023-02-13 23:06 UTC, avhitrov commented on internal/shortener/repositories/db_repository.go
> +	ticker := time.NewTicker(time.Millisecond * 500)
```
defer ticker.Stop()
```

2023-02-16 07:48 UTC, RomanAVolodin commented on internal/shortener/repositories/db_repository.go
> +func (repo *DatabaseRepository) DeleteRecords(ctx context.Context, userID uuid.UUID, ids []string) error {
Не смог убрать. Тогда DatabaseRepository перестанет реализовывать интерфейс Repository. 
Остальные хранилища (файловове и в памяти) все еще могут вернуть ошибку в этом месте.

2023-02-16 07:51 UTC, RomanAVolodin commented on internal/shortener/utils/repository_setter.go
> +			ToDelete: make(chan *entities.ItemToDelete),
Не смог придумать по какому принципу выбрать размер буфера в канале. Сделал 16. Не знаю почему :)

2023-02-16 08:11 UTC, RomanAVolodin commented on internal/shortener/repositories/file_repository.go
> +	if err = encoder.Encode(&repo.Storage); err != nil {
Я не очень понял, где именно и почему. 
Может быть голодание в момент сброса в файл, для избежания перенес освобождения блокировки до работы с файлом.

2023-02-16 08:24 UTC, RomanAVolodin commented on internal/shortener/repositories/file_repository.go
> +	if err = encoder.Encode(&repo.Storage); err != nil {
Немного погонял ручку DELETE /api/user/urls
![total_requests_per_second_1676535803](https://user-images.githubusercontent.com/32717824/219308585-f4fb25d8-b26b-49fd-a003-694a91cbc9a8.png)

2023-02-16 08:24 UTC, RomanAVolodin commented on internal/shortener/repositories/file_repository.go
> +	if err = encoder.Encode(&repo.Storage); err != nil {
![response_times_(ms)_1676535803](https://user-images.githubusercontent.com/32717824/219308690-4d0f21ea-a7a0-4623-b9d8-944b4826938d.png)

2023-02-16 08:25 UTC, RomanAVolodin commented on internal/shortener/repositories/file_repository.go
> +	if err = encoder.Encode(&repo.Storage); err != nil {
![number_of_users_1676535803](https://user-images.githubusercontent.com/32717824/219308751-bcf003ad-f5ed-4333-9d79-d879ac84043b.png)

2023-02-16 08:53 UTC, RomanAVolodin commented on internal/shortener/repositories/db_repository.go
> +		for range ticker.C {
Забываю про это постоянно :). Обернул в Lock/Unlock, не стал RLock/RUnlock там удаление происходит из хранилища.

2023-02-17 07:51 UTC, RomanAVolodin commented on internal/shortener/repositories/file_repository.go
> +	if err = encoder.Encode(&repo.Storage); err != nil {
Разобрались, починил

2023-02-19 22:12 UTC, avhitrov approved these changes
Надо проверить, работает ли проброс параметров в IN vs ANY. Все остальные вопросы проработаны.

2023-02-19 22:12 UTC, avhitrov commented on internal/shortener/repositories/db_repository.go
> +func (repo *DatabaseRepository) DeleteRecords(ctx context.Context, userID uuid.UUID, ids []string) error {
Да, все верно, мой недосмотр.

2023-02-19 22:12 UTC, avhitrov commented on internal/shortener/repositories/db_repository.go
> +		"UPDATE short_urls SET is_active=false WHERE user_id = ? AND id IN (?)",
Насколько я проблематику проброса параметров в SQL, в IN надо указывать список идентификаторов, а для того, чтобы пробросить слайс, как один параметр, необходимо задействовать ANY.
```suggestion
		"UPDATE short_urls SET is_active=false WHERE user_id = ? AND id=ANY(?)",
```
На 100% не помню, надо проверять. Поэтому не блокер.

2023-02-20 07:52 UTC, RomanAVolodin commented on internal/shortener/repositories/db_repository.go
> +		"UPDATE short_urls SET is_active=false WHERE user_id = ? AND id IN (?)",
у меня там sqlx.In , она ловко работает с IN. Саму строку запроса анализировал, там все как нужно.

2023-02-20 07:53 UTC, merged