Iter8
RomanAVolodin/go-url-shortener pull request #9
Opened 2023-01-02 19:02 UTC by RomanAVolodin

2023-01-11 22:07 UTC, avhitrov requested changes
Необходимо избавиться от log.Fatal в файловом репозитории. В остальном прекрасно.

2023-01-11 22:07 UTC, avhitrov commented on internal/shortener/handlers/shortener_handlers.go
> +func (h *ShortenerHandler) saveToRepositories(urlToEncode []byte) string {
Я правильно понимаю, что две репы заведены для реализации некоей мастер-слейв структуры? BackRepo для поиска, а основная репа - для генерации (которая считается медленной) новых id? Если да, то советую сохранить эту связку, чтобы потом, когда дело дойдет до бенчмарков, проверить, есть ли какой-нибудь выигрыш по сравнению с использованием единственной репы. Предполагаю, что можно создать некоторые условия, в которых выигрыш будет заметен. Одновременно делаю ставку на то, что это будут в лучшем случае единицы процентов. В любом случае, есть хороший задел на одну из поздних итераций.

2023-01-12 10:37 UTC, RomanAVolodin commented on internal/shortener/repositories/file_repository.go
> +		log.Fatal(err)
Поднимаю ошибку вверх  и там либо завершаю сервер, либо кидаю 500.

2023-01-12 10:42 UTC, RomanAVolodin commented on internal/shortener/handlers/shortener_handlers.go
> +func (h *ShortenerHandler) saveToRepositories(urlToEncode []byte) string {
Немного проще. Сейчас пока не добрались до базы данных, я сохраняю ссылки в двух репах. В первой:
{ id: url }, а во второй { url: id } , вторая нужна только лишь для O(1) поиска уже созданных ссылок, иначе каждый раз пришлось бы перебирать все при работе с одним репозиторием,  а это уже O(n)

2023-01-16 22:45 UTC, avhitrov commented on internal/shortener/handlers/shortener_handlers.go
> +func (h *ShortenerHandler) saveToRepositories(urlToEncode []byte) string {
👍

2023-01-16 22:47 UTC, avhitrov approved these changes
Отлично!

2023-01-20 17:54 UTC, merged